# Generated by Django 5.0.6 on 2024-05-31 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Gryffindor', 'Gryffindor'), ('Hufflepuff', 'Hufflepuff'), ('Ravenclaw', 'Ravenclaw'), ('Slytherin', 'Slytherin')], max_length=10, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('AES', 'Aprendices_de_las_Estrellas'), ('EXE', 'Exploradores_de_los_Encantos'), ('GCR', 'Guardianes_de_las_Criaturas'), ('MAM', 'Maestros_de_la_Magia')], max_length=3, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('habilidad_magica', models.CharField(max_length=100, null=True)),
                ('casa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APPMagic.casa')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('FIELDNAME', models.ManyToManyField(to='APPMagic.grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('profesion', models.CharField(max_length=30)),
                ('hechizo_favorito', models.CharField(max_length=100, null=True)),
                ('criatura_magica', models.CharField(max_length=100, null=True)),
                ('FIELDNAME', models.ManyToManyField(to='APPMagic.curso')),
            ],
        ),
    ]
