# Generated by Django 5.0.6 on 2024-05-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPMagic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
