# Generated by Django 5.0.6 on 2024-06-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPMagic', '0004_rename_fieldname_curso_grupos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('Curso',)},
        ),
        migrations.AlterField(
            model_name='curso',
            name='Curso',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
