# Generated by Django 5.0.6 on 2024-06-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPMagic', '0005_alter_curso_options_alter_curso_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='Cursos',
        ),
    ]
