# Generated by Django 5.0.6 on 2024-06-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPMagic', '0006_remove_profesor_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='Cursos',
            field=models.ManyToManyField(to='APPMagic.curso'),
        ),
    ]
