# Generated by Django 5.0.6 on 2024-06-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPMagic', '0008_publicacion_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_comentario',
            new_name='fecha_creacion',
        ),
    ]
